export default [
  "Sõda Venemaaga",
  "Krimm",
  "Vene okupatsioon",
  "Ukraina",
  "Volodõmõr Zelenski",
  "Olaf Scholz",
  "Valimised",
  "Venemaa käes",
  "Vene väed",
  "NATO",
  "Dmitri Medvedev",
  "Hanna Maljar",
  "Wagneri sõjakompanii",
  "Venemaa relvajõud",
  "Saksamaa",
  "Venemaa eesmärk",
  "Ukraina vastuvõtmine NATO-sse",
  "Luhanski oblast",
  "Zaporižžja oblast",
  "Hersoni oblast",
  "Krimmi vabastamine",
  "Venemaa eksistents",
  "Vaenlase suurtükirünnakud",
  "Vasturünnak",
  "Kaitserajatised",
  "Rajatud kaitseliinid",
  "Ettevaatlik tegutsemine",
  "NATO sõjaline komitee",
  "Venemaa kindlustused",
  "Moodsuundumused2023",
  "Tervislikud Retseptid",
  "Armsad Kutsikad",
  "Reisisihtkohad",
  "Aiandusnõuanded",
  "Kuulsuste Klats",
  "Tee-ise Projektid",
  "Fitness Motivatsioon",
  "Filmiarvustused",
  "Uusimad Tehnikavidinad",
  "Küpsetusõpetused",
  "Moetrendid2023",
  "Nutikadseadmed",
  "Fotograafianipid",
  "Dieedisoovitused",
  "Kunstiteraapia",
  "Rahatarkus",
  "Ajakirjanduseetika",
  "Suhtekorraldusstrateegiad",
  "Teadusteadlikkus",
  "Nutikad linnakud",
  "Taimehooldusnõuanded",
  "Ilutrendid2023",
  "Huumorivideod",
  "Emotsionaalne intellekt",
  "Digitaalne julgeolek",
  "Töökohtasuhted",
  "Muusikavideod",
  "Loodussäästlik eluviis",
  "Toiduretseptid",
  "Fototehnika",
  "Veinitootmine",
  "Filmiõpetus",
  "Taaskasutusideed",
  "Digitaalsed valimised",
  "Käsitöö projektid",
  "Fitness võistlused",
  "Spordialad",
  "Geograafia uuringud",
  "Kassid",
  "Teatrietendused",
  "Innovatiivsed tehnoloogiad",
  "Ökoloogiline jalajälg",
  "Kaugtöö",
  "Stiilitrendid2023",
  "Toataimed",
  "Põllumajandusarengud",
  "Eksootilised retseptid",
  "Matkahuvilised",
  "Rahvusvahelised uudised",
  "Kokakunst",
  "Innovatsiooni juhtimine",
  "Päevauudised",
  "Loomade käitumine",
  "Fotoprintimine",
  "Treeningrutiinid",
  "Kunstiajalugu",
  "Õmblusprojektid",
  "Ekstreemspordid",
  "Arvutimängud",
  "Toiduallergiad",
  "Virtuaalreaalsus",
  "Linnaplaneerimine",
  "Jalgpalli-uudised",
  "Retromoeilu",
  "Terapeutilised harjutused",
  "Ajaloo mõistatused",
  "Muusika instrumendid",
  "Podcast saated",
  "Botaanika",
  "Käsitsitegemised",
  "Merebioloogia",
  "Investeerimisnõuanded",
  "Reisipakkumised",
  "Autohooldus näpunäited",
  "Jooksmis nõuanded",
  "Fototehnika nipid",
  "Meresõiduhuvilised",
  "Filmiauhinnad",
  "Ehtekunst",
  "Psühholoogia videod",
  "Sotsiaalmeedia strateegiad",
  "Loomingulised projektid",
  "Terviseteadlikkus",
  "Aiakujundus ideed",
  "Värviteraapia",
  "Raamatuarvustused",
  "Majandusuudised",
  "Köök",
  "Aiandus",
  "Lilled",
  "Raha",
  "Investeerimin",
  "Eelarve",
  "Ministeerium",
  "Ilm",
  "Kastmine",
  "Taim",
  "Aed",
  "Aednik",
  "Kasvuhoone",
  "Kuiv maa",
  "Põud ja vihm",
  "Põuane",
]
